# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: golang:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: create golang project directory and link it
      run: |
        export REPO_NAME=$(dirname $${{ github.repository }})
        mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
        ln -svf $GITHUB_WORKSPACE $GOPATH/src/$REPO_NAME
        cd $GOPATH/src/$REPO_NAME

    # Runs a set of commands using the runners shell
    - name: build kitlab
      run: |
        env GOOS=darwin GOARCH=amd64 go build -o $GITHUB_WORKSPACE/kitlab